import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fibo Frontend Assignment",
  description: "Generated by create next app, build by Sahil Ahmed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-[#212121] relative`}>
        <div className="bottom-0 z-10 fixed min-w-[360px] h-[70px] w-full">
          <Navbar />
        </div>
        {children}
        
      </body>
    </html>
  );
}
